//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loango.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIVRE
    {
        public int Id_livre { get; set; }
        public string titre_livre { get; set; }
        public Nullable<int> USERId_user { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
